steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-key-server', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api-key-server']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-key-server'
      - '--image=gcr.io/$PROJECT_ID/api-key-server'
      - '--region=asia-northeast1'
      - '--set-env-vars=USE_SECRET_MANAGER=true,API_KEY_SERVER_GCP_PROJECT_ID=$PROJECT_ID,API_KEY_SERVER_MAX_TOKENS=8192,API_KEY_SERVER_REQUEST_TIMEOUT_SECONDS=240'
      # タイムアウト設定: 外部APIへのリクエストを含む全体の処理時間
      - '--timeout=300s'
      - '--no-allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/api-key-server'

# Timeout for the entire build (15 minutes)
timeout: 900s

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
